# Generated by Django 2.0.3 on 2020-04-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet', models.CharField(max_length=2250)),
                ('subject', models.CharField(max_length=2250)),
                ('fromuser', models.CharField(max_length=2250)),
                ('touser', models.CharField(max_length=2250)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usermessage', models.CharField(max_length=2250)),
                ('adminreply', models.CharField(default='', max_length=2250)),
            ],
        ),
        migrations.CreateModel(
            name='NOtStressTweets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notstresstweet', models.CharField(max_length=2250)),
                ('subject', models.CharField(max_length=2250)),
                ('fromuser', models.CharField(max_length=2250)),
                ('touser', models.CharField(max_length=2250)),
            ],
        ),
        migrations.CreateModel(
            name='Phishing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phishingtweet', models.CharField(max_length=2250)),
                ('subject', models.CharField(max_length=2250)),
                ('fromuser', models.CharField(max_length=2250)),
                ('touser', models.CharField(max_length=2250)),
            ],
        ),
        migrations.CreateModel(
            name='SentItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('senttweet', models.CharField(max_length=2250)),
                ('subject', models.CharField(max_length=2250)),
                ('fromuser', models.CharField(max_length=2250)),
                ('touser', models.CharField(max_length=2250)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stresstweet', models.CharField(max_length=2250)),
                ('subject', models.CharField(max_length=2250)),
                ('fromuser', models.CharField(max_length=2250)),
                ('touser', models.CharField(max_length=2250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('firstname', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='sentitems',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request1.User'),
        ),
        migrations.AddField(
            model_name='phishing',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request1.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request1.User'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request1.User'),
        ),
    ]
