# Generated by Django 2.0.3 on 2020-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('dob', models.DateTimeField()),
            ],
        ),
    ]
